<?php if ($this->pageCount): ?>
<div>
  <ul class="pagination justify-content-center pagination-sm">
  <!-- Previous page link -->
  <?php if (isset($this->previous)): ?>
    <li class="page-item">
      <a class="page-link" href="<?= $this->url($this->route, [], ['query' => ['page' => $this->previous]]) ?>">
        &lt;&lt;Poprzednia &lt;&lt;
      </a>    </li>

    </li>
  <?php else: ?>
    <li class="page-item disabled">
      <a class="page-link" href="#">
         &lt;&lt;Poprzednia &lt;&lt;
      </a>
  <?php endif ?>

  <!-- Numbered page links -->
  <?php foreach ($this->pagesInRange as $page): ?>
    <?php if ($page !== $this->current): ?>
      <li class="page-item">
        <a class="page-link" href="<?= $this->url($this->route, [], ['query' => ['page' => $page]]) ?>">
          <?= $page ?>
        </a>
      </li>
    <?php else: ?>
      <li class="page-item active" aria-current="page">
        <a class="page-link" href="#"><?= $page ?></a>
      </li>
    <?php endif ?>
  <?php endforeach ?>

  <!-- Next page link -->
  <?php if (isset($this->next)): ?>
    <li class="page-item">
      <a class="page-link" href="<?= $this->url($this->route, [], ['query' => ['page' => $this->next]]) ?>">
       &gt;&gt; Następna &gt;&gt;
      </a>
    </li>
  <?php else: ?>
    <li class="page-item disabled">
      <a class="page-link" href="#">
        &gt;&gt; Następna &gt;&gt;
      </a>
    </li>
  <?php endif ?>
  </ul>
</div>
<?php endif ?>
