<?php
 
$this->headLink()->appendStylesheet($this->basePath('css/kalendarz.css'));
$this->headScript()->appendFile($this->basePath('js/jquery.validate.min.js', 'text/javascript'));
$this->headScript()->appendFile($this->basePath('js/additional-methods.js', 'text/javascript'));
$this->headScript()->appendFile($this->basePath('js/messages_pl.js', 'text/javascript'));
$this->headScript()->appendFile($this->basePath('js/pokazWydarzenie.js', 'text/javascript'));


$title = 'Kalendarz miesiąca';
$this->headTitle($title);

$dzienMiesiacRok=strftime('%F', strtotime($data)); 
$rok= (int)substr($dzienMiesiacRok, 0, 4);
$miesiac=substr($dzienMiesiacRok, 5, 2);
$dzien= substr($dzienMiesiacRok, 8, 2);
$nastepnyRok=strftime('%F',mktime(0, 0, 0, $miesiac,   $dzien,   $rok+1));
$nastepnyMiesiac=strftime('%F',mktime(0, 0, 0, $miesiac+1,   $dzien,   $rok));
$poprzedniRok=strftime('%F',mktime(0, 0, 0, $miesiac,   $dzien,   $rok-1));
$poprzedniMiesiac=strftime('%F',mktime(0, 0, 0, $miesiac-1,   $dzien,   $rok));

$miesiac_ID='miesiac-'.date('Y-m', strtotime($data));

?>


 <?= $this->partial('partial/flashMessenger.phtml'); ?>

<div id="kalendarz">
       
<h3 style="text-align: center" id="<?= $miesiac_ID ?>"><?= 'Kalendarz dla '.$lekarz->getImie().' '.$lekarz->getNazwisko();   ?></h3>
<div class="panel_kalendarza">
    
    <div id="zdjecie"> <a href="<?= $this->url('kalendarz', ['action' => 'index','id'=>$lekarz->getIdlekarz(), 'data'=>$poprzedniRok])   ?>"><svg xmlns="http://www.w3.org/2000/svg" width="66" height="66" fill="orange" class="bi bi-skip-backward" viewBox="0 0 16 16">
  <path d="M.5 3.5A.5.5 0 0 1 1 4v3.248l6.267-3.636c.52-.302 1.233.043 1.233.696v2.94l6.267-3.636c.52-.302 1.233.043 1.233.696v7.384c0 .653-.713.998-1.233.696L8.5 8.752v2.94c0 .653-.713.998-1.233.696L1 8.752V12a.5.5 0 0 1-1 0V4a.5.5 0 0 1 .5-.5zm7 1.133L1.696 8 7.5 11.367V4.633zm7.5 0L9.196 8 15 11.367V4.633z"/></svg></a> </div>      
    <div id="zdjecie"> <a href="<?= $this->url('kalendarz', ['action' => 'index','id'=>$lekarz->getIdlekarz(),'data'=>$poprzedniMiesiac])   ?>"><svg xmlns="http://www.w3.org/2000/svg" width="66" height="66" fill="currentColor" class="bi bi-caret-left" viewBox="0 0 16 16">
  <path d="M10 12.796V3.204L4.519 8 10 12.796zm-.659.753l-5.48-4.796a1 1 0 0 1 0-1.506l5.48-4.796A1 1 0 0 1 11 3.204v9.592a1 1 0 0 1-1.659.753z"/></svg></a></div>     
<div class="srodkowy_panel_kalendarza"><span style="font-size: 34px;"><?= $naglowekKalendarza?> </span></div>
<div id="zdjecie"><a href="<?= $this->url('kalendarz', ['action' => 'index','id'=>$lekarz->getIdlekarz(),'data'=>$nastepnyMiesiac])   ?>"><svg xmlns="http://www.w3.org/2000/svg" width="66" height="66" fill="currentColor" class="bi bi-caret-right" viewBox="0 0 16 16">
  <path d="M6 12.796V3.204L11.481 8 6 12.796zm.659.753l5.48-4.796a1 1 0 0 0 0-1.506L6.66 2.451C6.011 1.885 5 2.345 5 3.204v9.592a1 1 0 0 0 1.659.753z"/></svg></a> </div>            
    <div id="zdjecie"><a href="<?= $this->url('kalendarz', ['action' => 'index','id'=>$lekarz->getIdlekarz(),'data'=>$nastepnyRok])   ?>"><svg xmlns="http://www.w3.org/2000/svg" width="66" height="66" fill="orange" class="bi bi-skip-forward" viewBox="0 0 16 16">
  <path d="M15.5 3.5a.5.5 0 0 1 .5.5v8a.5.5 0 0 1-1 0V8.752l-6.267 3.636c-.52.302-1.233-.043-1.233-.696v-2.94l-6.267 3.636C.713 12.69 0 12.345 0 11.692V4.308c0-.653.713-.998 1.233-.696L7.5 7.248v-2.94c0-.653.713-.998 1.233-.696L15 7.248V4a.5.5 0 0 1 .5-.5zM1 4.633v6.734L6.804 8 1 4.633zm7.5 0v6.734L14.304 8 8.5 4.633z"/></svg></a> </div> 
</div>

<?= $this->kodHTML;  ?>
 

<div style="padding-top:10px;"> 
 <a href="<?= $this->url('lekarz', ['action' => 'index']) ?>" title="Powrót do lekarzy" style="color: white;">
              <svg class="bi bi-caret-down-square" width="1.5em" height="1.5em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
  <path fill-rule="evenodd" d="M3.544 6.295A.5.5 0 0 1 4 6h8a.5.5 0 0 1 .374.832l-4 4.5a.5.5 0 0 1-.748 0l-4-4.5a.5.5 0 0 1-.082-.537z"/>
  <path fill-rule="evenodd" d="M14 1H2a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/>
              </svg><?= 'Powrót do zarządzania Lekarzami' ?>
</a>    
      
 <a href="<?= $this->url('kalendarz', ['action' => 'wpisz','id'=>$lekarz->getIdlekarz()]) ?>" title="Powrót do kalendarza" style="color: white; float: right;" id="noweWydarzenie">
            <?= 'Wpisz nowe Wydarzenie' ?>  <svg class="bi bi-caret-down-square" width="1.5em" height="1.5em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
  <path fill-rule="evenodd" d="M3.544 6.295A.5.5 0 0 1 4 6h8a.5.5 0 0 1 .374.832l-4 4.5a.5.5 0 0 1-.748 0l-4-4.5a.5.5 0 0 1-.082-.537z"/>
  <path fill-rule="evenodd" d="M14 1H2a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/>
              </svg>
 </a>             
    </div> 
</div>
<?php
$napis='Wydarzenie dla '.$this->lekarz->getImie().' '.$lekarz->getNazwisko(); 

?>

<!-- Modal #pokazWydarzenie-->
<div class="modal fade" id="pokazWydarzenie" tabindex="-1" aria-labelledby="pokazWydarzenieModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
          <h5 class="modal-title text-center" id="pokazWydarzenieModalLabel">
            <?= $napis ?><div id="pokazWydarzenieModalLabel2"></div></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" id="pokazWydarzenieladuj">
    
      </div>
      <div class="modal-footer">
             
   <button type="button" class="btn btn-secondary" data-dismiss="modal">       
 <a href="<?= $this->url('lekarz', ['action' => 'index']) ?>" title="Powrót do lekarzy" style="color: white;">
              <?= 'Powrót ' ?>
</a>    
                  
   </button>
    <button type="button" class="btn btn-primary" id="buttonusunWydarzenie2">
     <a href="<?= $this->url('kalendarz', ['action' => '#']) ?>" title="Usun wydarzenie" style="color: white; float: right;" id="usunjquery2">
            <?= 'Usuń Wydarzenie' ?> 
 </a>    
        
        
        </button>    
      </div>
    </div>
  </div>
</div>

<!-- Modal #wpiszWydarzenie-->
<div class="modal fade" id="wpiszWydarzenie" tabindex="-1" aria-labelledby="wpiszWydarzenieModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">Zamknij &times;</span>
        </button>
      </div>
      <div class="modal-body" id="wpiszWydarzeniemodalBody">
          <div id="wpiszWydarzeniemodalBody2"></div>
      </div>
     
    </div>
  </div>
</div>


<script type="text/javascript"> 
"use strict";


let foo = "<?= $this->escapeJs($rok) ?>";

let id=null;
let idlekarz=parseInt("<?= $this->escapeJs($lekarz->getIdlekarz()) ?>");
let dzien=null;

jQuery(function($){

let fx = {
    
// Dodaje nowe wydarzenie po jego zapisaniu do kodu HTML
"dodajWydarzenieDoKoduHtml" : function(data, formData){
// Przekształć łańcuch zapytania w obiekt
let entry = fx.deserialize(formData);

//nowy obiekt daty dla biezacego miesjaca
let kalendarz_biezacy_miesiac=new Date(NaN);

//nowy obiekt daty dla nowego Wydarzenie
let wydarzenie_nowe=new Date(NaN);

// Wyodrębnij miesiąc i rok z identyfikatora $miesiac_ID elementu h3
let idWydarzenie=$("h3").attr("id").split('-');

//console.log(idWydarzenie);
},
// Przeprowadza deserializację łańcucha zapytania i zwraca
// obiekt wydarzenia
"deserialize" : function(str){
// Rozbij parę nazwa-wartość
let data = str.split("&"),
// Deklaruj zmienne potrzebne w pętli
pairs=[], entry={}, key, val; 

// Przekształć każdą parę nazwa-wartość we właściwość obiektu
for (let x in data )
{
// Rozdziel każdą parę i zapisz otrzymane elementy w tablicy
pairs = data[x].split("=");
// Pierwszy element to nazwa parametru
key = pairs[0];
// Drugi element to wartość parametru
val = pairs[1];

// Przywróć łańcuchowi zakodowanemu w URL oryginalną postać
// i zapisz każdą wartość jako właściwość obiektu
entry[key] = fx.url_decode(val);
}

return entry;
},
// Dekoduje łańcuch zapytania
"url_decode" : function(str) {
// Zamienia znaki plus na spacje
let znaki_plus_na_spacje = str.replace(/\+/g, ' ');
// Zamienia encje na odpowiadające im znaki
return decodeURIComponent(znaki_plus_na_spacje);

},

// Sprawdza poprawność łańcucha daty (RRRR-MM-DD GG:MM:SS)
"kontrola_datyPK": function(date)
{
// Definiuj wyrażenie regularne, które będzie wzorcem poprawnego formatu np. 10:22
let pattern = /^ (\d{2})(:\d{2})$/;
// Zwróć true przy dopasowaniu albo false w przeciwnym wypadku
return date.match(pattern)!==null;
},
"kontrola_daty": function(date)
{
// Definiuj wyrażenie regularne, które będzie wzorcem poprawnego formatu np. 202`-12-12
let pattern =/^ (\d{4}(-\d{2}){2})$/;
// Zwróć true przy dopasowaniu albo false w przeciwnym wypadku
return date.match(pattern)!==null;
},

};





// Wyświetl wydarzenie w oknie modalnym
$("#kalendarz").on("click", ".link", function(event){

    event.preventDefault(); 
    $(this).addClass("active");
    
    let data = $(this).attr("href").replace(/.+?\?(.*)$/, "$1");
    let szukanyCiagid=/id=([0-9]{1,})/;
    //let szukanyciagidlekarz=/idlekarz=([0-9]{1,})/;
    let szukanadata=/data=([0-9]{4}-[0-9]{2}-[0-9]{2})/;
    let id1=data.match(szukanyCiagid);
    id=id1[1];
   // idlekarz=data.match(szukanyciagidlekarz);
    dzien=data.match(szukanadata);
    $('#pokazWydarzenie').modal('show');  
    
    $( "#pokazWydarzenieladuj" ).load( "http://localhost/przychodniadwa/kalendarz/pokaz-wydarzenie/2?id="+id+"&idlekarz="+idlekarz+"&data="+dzien[1]+" #tresc", function( response, status, xhr ) {
  if ( status == "error" ) {
    var msg = "Przepraszamy, pojawił się błąd : ";
    $( "#pokazWydarzenieladuj" ).html( msg + xhr.status + " " + xhr.statusText );
  }else{
      $("#buttonusunWydarzenie2").show();
  }
});

    $('#pokazWydarzenieModalLabel2').text('dla '+dzien[1]);
    
});
///////////////////////////////////////////////////////////////
////okno po kliku na usun wydarzenie 
$("body").on("click", "#usunjquery2", function(event){

    event.preventDefault(); 
    $(this).addClass("active");   
    
   // let data = $("#edytujid").attr("href").replace(/.+?\?(.*)$/, "$1");
    let data=$("#edytujidp").attr("wartosc");
    let szukanyCiagid=/([0-9]{1,})/;
    let id1=data.match(szukanyCiagid);
    let id=id1[1];
  
    $( ".modal-body" ).load( "../usunjquery/2?id="+id+" ", function( response, status, xhr ) {
    
  if ( status == "error" ) {
    var msg = "Przepraszamy, pojawił się błąd : ";
    $( ".modal-body" ).html( msg + xhr.status + " " + xhr.statusText );
  } else{
      $("#buttonusunWydarzenie2").hide("slow");
  }
    }); 
    
    
});
///////////////////////////////////////////////////////////////////

$("#kalendarz").on("click", "#noweWydarzenie", function(event){

    event.preventDefault(); 
    $(this).addClass("active");
   
   //  $("#wpiszWydarzeniemodalBody").html('');
     
    $('#wpiszWydarzenie').modal('show');  
     let form=null;
     
     let czyJest=$("#wpiszWydarzenieForm").length;

     if(!czyJest){
      $.ajax({
            method: "POST",
            url: "http://localhost/przychodniadwa/kalendarz/wpiszjquery/"+idlekarz,
            //data: "idlekarz="+idlekarz,
            dataType: "html",
            success: function(data){
      
            form = $(data).hide();
           // $("#wpiszWydarzeniemodalBody2").html('');
            form.appendTo("#wpiszWydarzeniemodalBody2")
            .fadeIn("slow");
            },
            error: function(msg){
            alert(msg);
                                }
            });
        }
});


// przycisk Zamknij - ukrywa okno modalne i warstwę maskującą
$("form").on("click", "button", function(event){
    
  $('#wpiszWydarzenie').modal('hide'); 
  // event.preventDefault();
});


});

</script>

