<?php
setlocale(LC_TIME, 'pl_PL.UTF-8', 'pl.UTF-8'); 
$this->headLink()->appendStylesheet($this->basePath('css/kalendarz.css'));
$kalendarz=new Kalendarz\Entity\Kalendarz($this->data);
$ilegodzinpracy=count($kalendarz->GODZINYPRACY);
$tablicaWydarzen=$this->tablicaWydarzen;
$data= strftime('%e %B %Y', strtotime($kalendarz->dataKalendarza));
 

$napis='Zaplanowane wydarzenia dla lekarza '.$lekarz->getImie().' '.$lekarz->getNazwisko().'<br>'.' w dniu '.$data.' r.';
 $licznik=0;

?>

<div id="kalendarz">
    <h4 style="text-align: center"><?= $napis  ?></h4>
    
   <?php for($i=0; $i<$ilegodzinpracy ; $i++):  ?> 
   
    <div class="godzina">
        <div class="tekst">
            <p> <em><?= $kalendarz->GODZINYPRACY[$i]  ?></em></p>
   </div>
    <div class="wiersz">
     <?php
     $godzina= substr($kalendarz->GODZINYPRACY[$i], 0, 2) ;
       $szerokosc=500;
     if(isset($tablicaWydarzen[$godzina])){
      $z_index=(int)8; 
      $licznikWydarzenie=0;
     foreach ($tablicaWydarzen[$godzina] as $wydarzenie){
     $minuty_jako_marginTop= substr($wydarzenie->getWydarzenie_start(), 3, 2);
     $szerokosc=$szerokosc+$minuty_jako_marginTop;
     $poczatek=new DateTime($wydarzenie->getWydarzenie_start());
     $koniec=new DateTime($wydarzenie->getWydarzenie_koniec());
     
     $dlugoscwydarzenia=$poczatek->diff($koniec,'i') ; 

     
     $wynik_height=($dlugoscwydarzenia->h*60)+$dlugoscwydarzenia->i;
      
     //$w=$dlugoscwydarzenia->format('%i');
     if($licznikWydarzenie==0){
     ?>
         
    <a href=<?= $this->url('kalendarz', ['action' => 'pokaz-wydarzenie', 'id' =>$wydarzenie->getIdWydarzenie(),'idlekarz'=>$lekarz->getIdlekarz()])  ?>
       style=" margin-top:<?= $minuty_jako_marginTop ?>px;height:<?= $wynik_height ?>px;background-color:<?= $kalendarz->KOLORY[$licznik++]  ?>;z-index:<?= $z_index ?>;" id="a"><?= $wydarzenie->getWydarzenie_tytul().' '.$poczatek->format('H:i').' - '.$koniec->format('H:i') ?></a> 
     
       
   <?php
   $licznikWydarzenie++;
     }else{?>
        
      <a href=<?= $this->url('kalendarz', ['action' => 'pokaz-wydarzenie', 'id' =>$wydarzenie->getIdWydarzenie(),'idlekarz'=>$lekarz->getIdlekarz()])  ?>
   style=" width:<?= $szerokosc ?>px; margin-top:<?= $minuty_jako_marginTop ?>px;height:<?= $wynik_height ?>px;background-color:<?= $kalendarz->KOLORY[$licznik++] ?>;z-index:<?= $z_index ?>;" id="a"><?= $wydarzenie->getWydarzenie_tytul().' '.$poczatek->format('H:i').' - '.$koniec->format('H:i') ?></a>   
     
     <?php
     $licznikWydarzenie++;
     
     }
     $z_index=$z_index-1;;    
     };
     }
     
     ?>

    </div>
     </div>
   
    <?php endfor; ?>
    <div style="padding-top:10px;"> 
 <a href="<?= $this->url('kalendarz', ['action' => 'index','id'=>$lekarz->getIdlekarz(),'data'=>$kalendarz->dataKalendarza]) ?>" title="Powrót do kalendarza" style="color: white;">
              <svg class="bi bi-caret-down-square" width="1.5em" height="1.5em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
  <path fill-rule="evenodd" d="M3.544 6.295A.5.5 0 0 1 4 6h8a.5.5 0 0 1 .374.832l-4 4.5a.5.5 0 0 1-.748 0l-4-4.5a.5.5 0 0 1-.082-.537z"/>
  <path fill-rule="evenodd" d="M14 1H2a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/>
              </svg><?= 'Powrót do kalendarza' ?>
             </a>    
    
    
    
    
   
 <a href="<?= $this->url('kalendarz', ['action' => 'wpisz','id'=>$lekarz->getIdlekarz()]) ?>" title="Powrót do kalendarza" style="color: white; float: right;">
            <?= 'Wpisz nowe Wydarzenie' ?>  <svg class="bi bi-caret-down-square" width="1.5em" height="1.5em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
  <path fill-rule="evenodd" d="M3.544 6.295A.5.5 0 0 1 4 6h8a.5.5 0 0 1 .374.832l-4 4.5a.5.5 0 0 1-.748 0l-4-4.5a.5.5 0 0 1-.082-.537z"/>
  <path fill-rule="evenodd" d="M14 1H2a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/>
              </svg></a> 
                
    
    </div> 
    
    
</div>
