<?php
setlocale(LC_TIME, 'pl_PL.UTF-8', 'pl.UTF-8'); 
$this->headLink()->appendStylesheet($this->basePath('css/kalendarz.css'));

$data= strftime('%e %B %Y', strtotime($wydarzenie->getWydarzenie_data()));
$poczatek= substr($wydarzenie->getWydarzenie_start() , 0,5);
$koniec=substr($wydarzenie->getWydarzenie_koniec() , 0,5);
?>

<div id="kalendarz" class="text-center">
  
    <h4><?=  'Wydarzenie dla '.$lekarz->getImie().' '.$lekarz->getNazwisko().' z dnia '.$data,' r.'    ?>  </h4>
     <div id="tresc">
    <p><?=  'Czas wydarzena od:'.$poczatek.' do: '.$koniec ?></p>
    <p><?=  'Nazwa wydarzenia: '.$wydarzenie->getWydarzenie_tytul() ?></p>
     <p><?=  $this->escapeHtml('Opis: '.$wydarzenie->getWydarzenie_opis()) ?></p>
    
 <div style="padding:10px;"> 
 <a href="<?= $this->url('kalendarz', ['action' => 'edytuj','id'=>$wydarzenie->getIdwydarzenie(),'data'=>$wydarzenie->getWydarzenie_data()]) ?>" title="Powrót do kalendarza" style="color: red; float: left;" id="edytujid">
              <svg class="bi bi-caret-down-square" width="1.5em" height="1.5em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
  <path fill-rule="evenodd" d="M3.544 6.295A.5.5 0 0 1 4 6h8a.5.5 0 0 1 .374.832l-4 4.5a.5.5 0 0 1-.748 0l-4-4.5a.5.5 0 0 1-.082-.537z"/>
  <path fill-rule="evenodd" d="M14 1H2a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/>
              </svg><?= ' Edytuj Wydarzenie' ?>
             </a>    
     </div>
     </div>
    
    
   
 <a href="<?= $this->url('kalendarz', ['action' => 'wpisz','id'=>$lekarz->getIdlekarz()]) ?>" title="Powrót do kalendarza" style="color: white; float: right;">
            <?= 'Wpisz nowe Wydarzenie' ?>  <svg class="bi bi-caret-down-square" width="1.5em" height="1.5em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
  <path fill-rule="evenodd" d="M3.544 6.295A.5.5 0 0 1 4 6h8a.5.5 0 0 1 .374.832l-4 4.5a.5.5 0 0 1-.748 0l-4-4.5a.5.5 0 0 1-.082-.537z"/>
  <path fill-rule="evenodd" d="M14 1H2a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/>
              </svg></a> 
                
    
    </div>     
    