<?php
$this->headTitle('Edycja Uprawnień Roli');

$form->get('submit')
        ->setAttributes(['class'=>'btn btn-primary']);

$csrf=$form->get('csrf');
$submit=$form->get('submit');


$form->prepare();

echo $this->form()->openTag($form);
    
?>
<div class="row">
    
	<div class="col-sm-8 offset-sm-2">
		<div class="border-bottom mt-4 pb-2 text-center">
			<div class="alert alert-info" role="alert">
				<h4><svg xmlns="http://www.w3.org/2000/svg" width="36" height="36" fill="currentColor" class="bi bi-list-task" viewBox="0 0 16 16">
  <path fill-rule="evenodd" d="M2 2.5a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5V3a.5.5 0 0 0-.5-.5H2zM3 3H2v1h1V3z"/>
  <path d="M5 3.5a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9a.5.5 0 0 1-.5-.5zM5.5 7a.5.5 0 0 0 0 1h9a.5.5 0 0 0 0-1h-9zm0 4a.5.5 0 0 0 0 1h9a.5.5 0 0 0 0-1h-9z"/>
  <path fill-rule="evenodd" d="M1.5 7a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5H2a.5.5 0 0 1-.5-.5V7zM2 7h1v1H2V7zm0 3.5a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5H2zm1 .5H2v1h1v-1z"/>
</svg> Edytuj Uprawnienia Roli "<?= $rola->getName();   ?>"</h4>
                                <div class="text-danger ">
				<?= ($bledy) ? ('W formularzu występują błędy. Popraw je !!') : null ?>
                                </div>
			</div>
		</div>

            <?= $this->partial('partial/flashMessenger.phtml'); ?>
            
		<div class="card">
			
			<div class="card-body">
				
				 <table class="table table-striped table-bordered">
            <tr>
                <th>Nazwa</th>
                <th>Opis</th>
            </tr>
            <?php foreach ($uprawnieniaAll as $permission):
     
             $element = $form->get('uprawnienie')->get($permission['name']);
            
            ?>
            <tr>
                <td>
                    <div class="checkbox">
                        <label><input type="checkbox" name="<?= $this->escapeHtmlAttr($element->getName()) ?>" 
                                      value="<?= $this->escapeHtmlAttr($element->getCheckedValue()) ?>"
                                      <?php if ($element->isChecked()) echo 'checked'?>
                                      <?php if ($element->getAttribute('disabled')) echo 'disabled'?>>
                            <?= $this->escapeHtml($element->getLabel()) ?>
                        </label>
                        <?= $this->formElementErrors($element); ?>                  
                    </div>
                </td>
                <td>
                    <?= $this->escapeHtml($permission['opis']) ?>
                </td>
            </tr>
            <?php endforeach; ?>
        </table>	
 
                            <div class="col-sm-12  btn btn-secondary btn-lg btn-block">
                                 
                                <?=  $this->formHidden($csrf);  ?>     
                                <?=  $this->formSubmit($submit);  ?>
                            </div>
    
                        </div>
                </div>
        </div>
</div>
  <?= $this->form()->closeTag();  ?>