<?php 
$title = 'Rejestracja Roli';
$this->headTitle(($title));


$form->setAttribute('id', 'dodajRole');
$form->setAttributes([
    'class'=>"form-horizontal",
]);


$name=$form->get('name');
//$name->setLabel('Wpisz nazwę roli:');
$name->setAttributes([
    'id'=>'name',   
    'class' => 'form-control',
]);
$name->setLabelAttributes([
    'class'=> 'col-sm-4 col-form-label',
    'for'=>'name',
    ]);

$idrola=$form->get('idrola');

$opis=$form->get('opis');
$opis->setAttributes([
    'id'=>'opis',   
    'class' => 'form-control',
]);
$opis->setLabelAttributes([
    'class'=> 'col-sm-4 col-form-label',
    'for'=>'opis',
    ]);


$multi_checkbox=$form->get('multi_checkbox');

$multi_checkbox->setAttributes([
    'id'=>'multi_checkbox',   
    'class' => 'form-control',
]);
$multi_checkbox->setLabelAttributes([
    'class'=> 'col-sm-4 col-form-label',
    'for'=>'multi_checkbox',
    ]);

$tablica=  [ 
            [
                'value' => '0',
                'label' => 'Apple',
                'selected' => false,
                'disabled' => true,
                'attributes' => [
                    'id' => 'apple_option',
                    'data-fruit' => 'apple',
                ],
                'label_attributes' => [
                    'id' => 'apple_label',
                ],
            ],
            [
                'value' => '1',
                'label' => 'Orange',
                'selected' => true,
            ],
            [
                'value' => '2',
                'label' => 'Lemon',
            
        ],

];

//print_r($tablica);

$multi_checkbox->setValueOptions($tablicaOpcji);
//print_r($multi_checkbox->getValueOptions());
//exit();

$submit=$form->get('submit');
$csrf=$form->get('csrf');


$form->prepare();

echo $this->form()->openTag($form);

?>
<div class="row">
    
	<div class="col-sm-8 offset-sm-2">
		<div class="border-bottom mt-4 pb-2 text-center">
			<div class="alert alert-info" role="alert">
				<h4><svg xmlns="http://www.w3.org/2000/svg" width="36" height="36" fill="currentColor" class="bi bi-people" viewBox="0 0 16 16">
  <path d="M15 14s1 0 1-1-1-4-5-4-5 3-5 4 1 1 1 1h8zm-7.978-1A.261.261 0 0 1 7 12.996c.001-.264.167-1.03.76-1.72C8.312 10.629 9.282 10 11 10c1.717 0 2.687.63 3.24 1.276.593.69.758 1.457.76 1.72l-.008.002a.274.274 0 0 1-.014.002H7.022zM11 7a2 2 0 1 0 0-4 2 2 0 0 0 0 4zm3-2a3 3 0 1 1-6 0 3 3 0 0 1 6 0zM6.936 9.28a5.88 5.88 0 0 0-1.23-.247A7.35 7.35 0 0 0 5 9c-4 0-5 3-5 4 0 .667.333 1 1 1h4.216A2.238 2.238 0 0 1 5 13c0-1.01.377-2.042 1.09-2.904.243-.294.526-.569.846-.816zM4.92 10A5.493 5.493 0 0 0 4 13H1c0-.26.164-1.03.76-1.724.545-.636 1.492-1.256 3.16-1.275zM1.5 5.5a3 3 0 1 1 6 0 3 3 0 0 1-6 0zm3-2a2 2 0 1 0 0 4 2 2 0 0 0 0-4z"/>
</svg>  Zarejestruj nową Rolę w systemie !</h4>
                                <div class="text-danger ">
				<?= isset($messages) ? ('W formularzu występują błędy. Popraw je !!') : null ?>
                                </div>
			</div>
		</div>

            <?= $this->partial('partial/flashMessenger.phtml'); ?>
            
		<div class="card">
			
			<div class="card-body">
				
					<div class="form-group row">
						<?=  $this->formLabel($name); ?>
						<div class="col-sm-6">
						<?php
                                                echo $this->formText($name);
                                                $name->getMessages();
                                               echo $this->formElementErrors()->render($name, ['class' => 'text-danger']);
                                                ?>
						</div>
					</div>

					<div class="form-group row">
						<?=  $this->formLabel($opis); ?>
						<div class="col-sm-6">
						<?php
                                                echo $this->formTextarea($opis);
                                                $opis->getMessages();
                                                echo $this->formElementErrors()->render($opis, ['class' => 'text-danger']);
                                                ?>
						</div>
					</div>
                            
                            
                            <div class="form-group row">
						<?=  $this->formLabel($multi_checkbox); ?>
						<div class="col-sm-8 input-group text-center">
						<?php
                                                echo $this->formMultiCheckbox($multi_checkbox);
                                                $opis->getMessages();
                                                echo $this->formElementErrors()->render($multi_checkbox, ['class' => 'text-danger']);
                                                ?>
						</div>
					</div>

                            
                            <div class="col-sm-12  btn btn-secondary btn-lg btn-block">
                                <?=  $this->formHidden($form->get('idrola'));  ?>   
                                <?=  $this->formHidden($csrf);  ?>     
                                <?=  $this->formSubmit($submit);  ?>
                            </div>
    
                        </div>
                </div>
        </div>
</div>
  <?= $this->form()->closeTag();  ?>



