<?php
$title = 'Usuwanie Roli';
$this->headTitle($this->escapeHtml($title));
?>

<div class="row">
    
	<div class="col-sm-8 offset-sm-2">
		<div class="border-bottom mt-4 pb-2 text-center">
			<div class="alert alert-info" role="alert">
				<h4><svg xmlns="http://www.w3.org/2000/svg" width="36" height="36" fill="currentColor" class="bi bi-scissors" viewBox="0 0 16 16">
  <path d="M3.5 3.5c-.614-.884-.074-1.962.858-2.5L8 7.226 11.642 1c.932.538 1.472 1.616.858 2.5L8.81 8.61l1.556 2.661a2.5 2.5 0 1 1-.794.637L8 9.73l-1.572 2.177a2.5 2.5 0 1 1-.794-.637L7.19 8.61 3.5 3.5zm2.5 10a1.5 1.5 0 1 0-3 0 1.5 1.5 0 0 0 3 0zm7 0a1.5 1.5 0 1 0-3 0 1.5 1.5 0 0 0 3 0z"/>
</svg>  Usuń  Rolę z systemu !</h4>
                                <div class="text-danger ">
				<?= 'Czy jesteś pewien że chcesz usunąć Rolę i wszystkie dowiązania do niej?' ?>
                                </div>
			</div>
		</div>
            
            <div class="card">
			
                <div class="card-body">
                    
                  <ul class="list-group">   
            <li class="list-group-item"><?= $this->escapeHtml($rola->getName()) ?></li>
                </ul>

                <form action="<?php $this->url('rola', ['action'=>'usun'], true) ?>" method="post">
                    <input type="hidden" name="id" value="<?= $this->escapeHtmlAttr($rola->getIdrola()) ?>" />
                    <input class="btn btn-primary" type="submit" name="confirm" value="Rezygnuję" />
                    <input class="btn btn-danger" type="submit" name="confirm" value="Usuwam" />
                </form>
                    
                </div>
            </div>
        </div>
</div>
