<?php

$wskaznik=0;
if($wpisz_czy_edytuj=='edytuj')
{
    if($lekarz){
   $napisLogo='Edytuj Wydarzenie dla '.$this->lekarz->getImie().' '.$lekarz->getNazwisko();
    }else{
        $napisLogo='Edytuj Wydarzenie dla wszystkich lekarzy !';
    }
    $wskaznik=1;
}else{
    $napisLogo='Zarejestruj nowe Wydarzenie w systemie !';
}
if($this->lekarz){
 ?>
<div id="napisLogo" opis="<?= $this->lekarz->getImie().' '.$lekarz->getNazwisko() ?>"></div>   
 <?php
}
$form->setAttribute('id', 'wpiszWydarzenie');
$form->setAttributes([
    'class'=>"form-horizontal",
]);


$wydarzenieFieldset=$form->get('wydarzenie_fieldset');

$wydarzenieIdlekarz=$wydarzenieFieldset->get('wydarzenie_idlekarz');

if($this->lekarz instanceof Application\Model\Lekarz)
{
    $wydarzenieIdlekarz->setValue($this->lekarz->getIdlekarz());
}

$wydarzenieTytul=$wydarzenieFieldset->get('wydarzenie_tytul');
$wydarzenieTytul->setAttributes([
    'id'=>'tytul',   
    'class' => 'form-control',
]);
$wydarzenieTytul->setLabelAttributes([
    'class'=> 'col-sm-4 col-form-label',
    'for'=>'tytul',
    ]);

$wydarzenieOpis=$wydarzenieFieldset->get('wydarzenie_opis');
$wydarzenieOpis->setAttributes([
    'id'=>'opis',   
    'class' => 'form-control',
]);
$wydarzenieOpis->setLabelAttributes([
    'class'=> 'col-sm-4 col-form-label',
    'for'=>'opis',
    ]);
$wydarzenieStart=$wydarzenieFieldset->get('wydarzenie_start');
$wydarzenieStart->setAttributes([
    'id'=>'start',   
    'class' => 'form-control',
]);
$wydarzenieStart->setLabelAttributes([
    'class'=> 'col-sm-4 col-form-label',
    'for'=>'start',
    ]);

$wydarzenieKoniec=$wydarzenieFieldset->get('wydarzenie_koniec');
$wydarzenieKoniec->setAttributes([
    'id'=>'koniec',   
    'class' => 'form-control',
]);
$wydarzenieKoniec->setLabelAttributes([
    'class'=> 'col-sm-4 col-form-label',
    'for'=>'koniec',
    ]);

$wydarzenieData=$wydarzenieFieldset->get('wydarzenie_data');
$wydarzenieData->setAttributes([
    'id'=>'data',   
    'class' => 'form-control',
]);
$wydarzenieData->setLabelAttributes([
    'class'=> 'col-sm-4 col-form-label',
    'for'=>'data',
    ]);

if(!$wskaznik){
$checkbox=$form->get('checkbox');
$checkbox->setAttributes([
    'id'=>'checkbox',   
    'class' => 'form-control',
]);
$checkbox->setLabelAttributes([
    'class'=> 'col-sm-4 col-form-label',
    'for'=>'checkbox',
    'id'=>'checkbox_label'
    ]);
if(!$checkbox->isChecked()){
   $checkbox->setLabel('Dokonujesz wpisu dla wszystkich lekarzy');
   $checkbox->setLabelAttributes([
    'class'=> 'col-sm-4 col-form-label bg-danger',
       'id'=>'checkbox_label'
    ]);
}
}



$submit=$form->get('submit');


$csrf=$form->get('csrf');

$form->prepare();

echo $this->form()->openTag($form);

?>
<div class="row">
    
	<div class="col-sm-8 offset-sm-2">
		<div class="border-bottom mt-4 pb-2 text-center">
			<div class="alert alert-info" role="alert">
				<h4><svg xmlns="http://www.w3.org/2000/svg" width="36" height="36" fill="currentColor" class="bi bi-people" viewBox="0 0 16 16">
  <path d="M15 14s1 0 1-1-1-4-5-4-5 3-5 4 1 1 1 1h8zm-7.978-1A.261.261 0 0 1 7 12.996c.001-.264.167-1.03.76-1.72C8.312 10.629 9.282 10 11 10c1.717 0 2.687.63 3.24 1.276.593.69.758 1.457.76 1.72l-.008.002a.274.274 0 0 1-.014.002H7.022zM11 7a2 2 0 1 0 0-4 2 2 0 0 0 0 4zm3-2a3 3 0 1 1-6 0 3 3 0 0 1 6 0zM6.936 9.28a5.88 5.88 0 0 0-1.23-.247A7.35 7.35 0 0 0 5 9c-4 0-5 3-5 4 0 .667.333 1 1 1h4.216A2.238 2.238 0 0 1 5 13c0-1.01.377-2.042 1.09-2.904.243-.294.526-.569.846-.816zM4.92 10A5.493 5.493 0 0 0 4 13H1c0-.26.164-1.03.76-1.724.545-.636 1.492-1.256 3.16-1.275zM1.5 5.5a3 3 0 1 1 6 0 3 3 0 0 1-6 0zm3-2a2 2 0 1 0 0 4 2 2 0 0 0 0-4z"/>
</svg><?php echo $napisLogo; ?></h4>
                                <div class="text-danger ">
				<?= isset($messages) ? ('W formularzu występują błędy. Popraw je !!') : null ?>
                                </div>
			</div>
		</div>

            
		<div class="card">
			
			<div class="card-body">
                        <?php     if(!$wskaznik):  ?>
                                <div class="form-group row">
						<?=  $this->formLabel($checkbox); ?>
						<div class="col-sm-8 input-group text-center">
						<?php
                                                echo $this->formCheckbox($checkbox);
                                                $checkbox->getMessages();
                                                echo $this->formElementErrors()->render($checkbox, ['class' => 'text-danger']);
                                                ?>
						</div>
					</div>
                            <?php endif; ?>
				
					<div class="form-group row">
						<?=  $this->formLabel($wydarzenieTytul); ?>
						<div class="col-sm-6">
						<?php
                                                echo $this->formText($wydarzenieTytul);
                                                $wydarzenieTytul->getMessages();
                                               echo $this->formElementErrors()->render($wydarzenieTytul, ['class' => 'text-danger']);
                                                ?>
						</div>
					</div>

					<div class="form-group row">
						<?=  $this->formLabel($wydarzenieOpis); ?>
						<div class="col-sm-6">
						<?php
                                                echo $this->formTextarea($wydarzenieOpis);
                                                $wydarzenieOpis->getMessages();
                                                echo $this->formElementErrors()->render($wydarzenieOpis, ['class' => 'text-danger']);
                                                ?>
						</div>
					</div>
                            
                            
                            <div class="form-group row">
						<?=  $this->formLabel($wydarzenieStart); ?>
						<div class="col-sm-8 input-group text-center">
						<?php
                                                echo $this->formTime($wydarzenieStart);
                                                $wydarzenieStart->getMessages();
                                                echo $this->formElementErrors()->render($wydarzenieStart, ['class' => 'text-danger']);
                                                ?>
						</div>
					</div>
                            
                            <div class="form-group row">
						<?=  $this->formLabel($wydarzenieKoniec); ?>
						<div class="col-sm-8 input-group text-center">
						<?php
                                                echo $this->formTime($wydarzenieKoniec);
                                                $wydarzenieKoniec->getMessages();
                                                echo $this->formElementErrors()->render($wydarzenieKoniec, ['class' => 'text-danger']);
                                                ?>
						</div>
					</div>
                            
                            <div class="form-group row">
						<?=  $this->formLabel($wydarzenieData); ?>
						<div class="col-sm-8 input-group text-center">
						<?php
                                                echo $this->formDate($wydarzenieData);
                                                $wydarzenieData->getMessages();
                                                echo $this->formElementErrors()->render($wydarzenieData, ['class' => 'text-danger']);
                                                ?>
						</div>
					</div>

                            
                            <div class="col-sm-12  btn btn-secondary btn-lg btn-block">
                                <?=  $this->formHidden($wydarzenieIdlekarz);  ?>   
                                <?=  $this->formHidden($csrf);  ?>     
                                <?=  $this->formSubmit($submit);  ?>
                            </div>
    
                        </div>
                </div>
        </div>
</div>
  <?= $this->form()->closeTag();  ?>


<script type="text/javascript"> 
"use strict";
 
 let input = $( "form input:checkbox" )
  //.wrap( "<span></span>" )
  .parent()
  .css({
    background: "white",
   // border: "1px red solid"
  });
 

let napisPierwotny='Dokonujesz wpisu dla '+ $('#napisLogo').attr('opis');

 let napis='Dokonujesz wpisu dla wszystkich lekarzy';
 //console.log(napisLabal);
 
 $( "form input:checkbox" ).click(function(){
     
    let wynik =$(this).is( ":checked" ); 

     if(!wynik){
        $('#checkbox_label').addClass('bg-danger'); 
        $('#checkbox').parent().css("background-color", "white");
        $('#checkbox_label').text(napis);
     }else{
         $('#checkbox_label').removeClass('bg-danger');
         $('#checkbox_label').text(napisPierwotny);
         $('#checkbox').parent().css({ background: "yellow"});
     }    
 });
 
 </script>
