<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<?= $this->doctype() ?>
<html lang="pl">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Przychodnia')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript()  
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.5.1.min.js')) 
        ?>    
    </head>
    <body>      
        <nav class="navbar navbar-expand-lg navbar-light" style="background-color: blue;">
           <div class="container">
            <a class="navbar-brand" href="<?= $this->url('home') ?>">
                <img src="<?= $this->basePath('img/logo-przychodnia.png') ?>" alt="Przychodnia" width="175">
                    </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
        
     <!--   
      <li class="nav-item active">
        <a class="nav-link" href="<?php //echo $this->url('home') ?>">Strona główna <span class="sr-only">(current)</span></a>
      </li>
      -->
      
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Strona główna
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="<?= $this->url('home') ?>">Wybierz lekarza</a>
          <a class="dropdown-item" href="<?= $this->url('pokaz',['action' => 'dodaj']) ?>">Pokaz</a>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>  
      
      
       <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Lekarze
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="<?= $this->url('lekarz') ?>">zarządzaj</a>
          <a class="dropdown-item" href="<?= $this->url('lekarz',['action' => 'dodaj']) ?>">dodaj</a>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
       <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Użytkownicy
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="<?= $this->url('uzytkownik') ?>">zarządzaj</a>
          <a class="dropdown-item" href="<?= $this->url('uzytkownik',['action' => 'dodaj']) ?>">dodaj</a>
          <a class="dropdown-item" href="<?= $this->url('uzytkownik',['action' => 'pokaz']) ?>">Pokaż.......</a>
        </div>
      </li>
      
      
      
      <li class="nav-item">
        <a class="nav-link" href="<?= $this->url('login') ?>">Loguj</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<?= $this->url('login',['action' => 'wyloguj'])?>">Wyloguj</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<?= $this->url('rejestruj')?>">Zarejestruj się</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          RBAC Zarządzaj
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="<?= $this->url('rola')?>">Role</a>
          <a class="dropdown-item" href="<?= $this->url('rola',['action' => 'dodaj'])?>">Dodaj Rolę</a>
         <a class="dropdown-item" href="<?= $this->url('uprawnienia')?>">Uprawnienia</a>
         <a class="dropdown-item" href="<?= $this->url('uprawnienia',['action' => 'dodaj'])?>">Dodaj Uprawnienie</a>
        </div>
      </li>
    </ul>
  </div>
  </div>
</nav>
        <div class="container">
        
              <?= $this->partial('partial/loguj_wyloguj.phtml'); ?>
        </div>
        
        
        <div class="container">
            
            <?= $this->content ?>
            
            <hr>
            <footer>
                <p>&copy; <?= date('Y') ?> <a href="<?= $this->url('home') ?>">Przychodnia</a> LS Company S.A..</p>
            </footer>
        </div>
     
        
        
        <?= $this->inlineScript()
          
                ?>
    </body>
</html>
