<?php 
$this->headScript()->appendFile($this->basePath('js/jquery.validate.min.js', 'text/javascript'));
$this->headScript()->appendFile($this->basePath('js/additional-methods.js', 'text/javascript'));
$this->headScript()->appendFile($this->basePath('js/additional-methods_PL.js', 'text/javascript'));
$this->headScript()->appendFile($this->basePath('js/messages_pl.js', 'text/javascript'));
$this->headScript()->appendFile('//cdn.ckeditor.com/4.15.1/standard/ckeditor.js', 'text/javascript');

$title = 'Edycja  Lekarza';
$this->headTitle($title);

$form=$this->form;
//$form->setAttribute('action', $this->url('lekarz', ['action' => 'edytuj','id'=>$lekarz->getIdlekarz()]));
$form->setAttribute('action', $this->url('lekarz', ['action' => 'edytuj','id'=>$lekarz->getIdlekarz()]));
$form->setAttribute('method', 'POST');
$form->setAttribute('id', 'dodaj_form_lekarz');
$form->setAttribute('enctype', 'multipart/form-data');
$form->setAttributes([
    'class'=>"form-horizontal",
]);

$imie=$form->get('lekarz_fieldset')->get('imie');
$imie->setAttributes([
    'id'=>'imie',   
    'class' => 'form-control',
    'placeholder'=>'Podaj imię:',
]);
$imie->setLabelAttributes([
       'class'=> 'col-sm-4 col-form-label',
    'for'=>'imie',
    ]);

$nazwisko=$form->get('lekarz_fieldset')->get('nazwisko');
$nazwisko->setAttributes([
    'id'=>'nazwisko',   
    'class' => 'form-control',
    'placeholder'=>'Podaj nazwisko:',
]);
$nazwisko->setLabelAttributes([
       'class'=> 'col-sm-4 col-form-label',
    ]);

$pesel=$form->get('lekarz_fieldset')->get('pesel');
$pesel->setAttributes([
    'id'=>'pesel',   
    'class' => 'form-control',
    'placeholder'=>'Podaj PESEL:',
]);
$pesel->setLabelAttributes([
       'class'=> 'col-sm-4 col-form-label',
    ]);

$mail=$form->get('lekarz_fieldset')->get('mail');
$mail->setAttributes([
    'id'=>'mail',   
    'class' => 'form-control',
    'placeholder'=>'Podaj mail:',
]);
$mail->setLabelAttributes([
       'class'=> 'col-sm-4 col-form-label',
    ]);

$mail2=$form->get('confirm_mail');
$mail2->setAttributes([
    'id'=>'mail2',   
    'class' => 'form-control',
    'placeholder'=>'Powtórz mail:',
]);
$mail2->setLabelAttributes([
       'class'=> 'col-sm-4 col-form-label',
    ]);

$specjalnosc=$form->get('lekarz_fieldset')->get('specjalnosc');;
$specjalnosc->setAttributes([
    'id'=>'specjalnosc',   
    'class' => 'form-control',
    'placeholder'=>'Podaj specjalność:',
]);
$specjalnosc->setLabelAttributes([
       'class'=> 'col-sm-4 col-form-label',
    ]);

$telefon=$form->get('lekarz_fieldset')->get('telefon');;
$telefon->setAttributes([
    'id'=>'telefon',   
    'class' => 'form-control',
    'placeholder'=>'Podaj specjalność:',
]);
$telefon->setLabelAttributes([
       'class'=> 'col-sm-4 col-form-label',
    ]);

$opis=$form->get('lekarz_fieldset')->get('opis');;
$opis->setAttributes([
    'id'=>'opis',   
    'class' => 'form-control',
    'placeholder'=>'Podaj specjalność:',
]);
$opis->setLabelAttributes([
       'class'=> 'col-sm-4 col-form-label',
    ]);



$file=$form->get('file');
$file->setAttributes([ 
    'class' => 'form-control',
]);

$hiddenId=$form->get('lekarz_fieldset')->get('idlekarz');
$hiddenId->setAttributes([
    'id'=>'idlekarz',   
]);

$submit=$form->get('submit');
$submit->setAttributes([
'class' => 'btn btn-primary',
]);
$submit->setValue('Edytuj Lekarza');



$form->prepare();

echo $this->form()->openTag($form);
    
?>
<div class="row">
    
	<div class="col-sm-8 offset-sm-2">
		<div class="border-bottom mb-4 mt-4 pb-2">
			<div class="alert alert-info" role="alert">
				<h4>Edycja lekarza: <?= $lekarz->getImie().' '.$lekarz->getNazwisko();   ?></h4>
				
			</div>
		</div>

		<div class="card">
			<div class="card-header">
				<h3 class="card-text">Wypełnij formularz i wyślij</h3>
			</div>
			<div class="card-body">
				
					<div class="form-group row">
						<?=  $this->formLabel($imie); ?>
						<div class="col-sm-6">
						<?php
                                                echo $this->formText($imie);
                                                $imie->getMessages();
                                               echo $this->formElementErrors()->render($imie, ['class' => 'text-danger']);
                                                ?>
						</div>
					</div>

					<div class="form-group row">
						<?=  $this->formLabel($nazwisko); ?>
						<div class="col-sm-6">
						<?php
                                                echo $this->formText($nazwisko);
                                                $nazwisko->getMessages();
                                                echo $this->formElementErrors()->render($nazwisko, ['class' => 'text-danger']);
                                                ?>
						</div>
					</div>

					<div class="form-group row">
						<?=  $this->formLabel($pesel); ?>
						<div class="col-sm-6">
						<?php
                                                echo $this->formText($pesel);
                                                $pesel->getMessages();
                                                echo $this->formElementErrors()->render($pesel, ['class' => 'text-danger']);
                                                ?>
						</div>
					</div>

					<div class="form-group row">
						<?=  $this->formLabel($mail); ?>
						<div class="col-sm-6">
						<?php
                                                echo $this->formEmail($mail);
                                                $mail->getMessages();
                                                echo $this->formElementErrors()->render($mail, ['class' => 'text-danger']);
                                                ?>
						</div>
					</div>

					<div class="form-group row">
						<?=  $this->formLabel($mail2); ?>
						<div class="col-sm-6">
						<?php
                                                echo $this->formEmail($mail2);
                                                $mail2->getMessages();
                                                echo $this->formElementErrors()->render($mail2, ['class' => 'text-danger']);
                                                ?>
						</div>
					</div>

					<div class="form-group row">
						<?=  $this->formLabel($specjalnosc); ?>
						<div class="col-sm-6">
						<?php
                                                echo $this->formText($specjalnosc);
                                                $specjalnosc->getMessages();
                                                echo $this->formElementErrors()->render($specjalnosc, ['class' => 'text-danger']);
                                                ?>
						</div>
					</div>

					<div class="form-group row">
						<?=  $this->formLabel($telefon); ?>
						<div class="col-sm-6">
						<?php
                                                echo $this->formTel($telefon);
                                                $telefon->getMessages();
                                                echo $this->formElementErrors()->render($telefon, ['class' => 'text-danger']);
                                                ?>
						</div>
					</div>
                            <div class="form-group row">
						<?=  $this->formLabel($opis); ?>
						<div class="col-sm-6">
						<?php
                                                echo $this->formTextarea($opis);
                                                $opis->getMessages();
                                                echo $this->formElementErrors()->render($opis, ['class' => 'text-danger']);
                                                ?>
						</div>
					</div>
<div class="form-group row">
    <div col-sm-4 col-form-label>
         <div class="float-left">
             <?php
             
           $link=$this->lekarz->getZdjecie();
              if(!$link){
                 $link='/public/img/Anonymous_male.jpg';
              }
              
             ?>
     <figure class="figure">
   <img width="200" class="rounded mx-auto d-block img-thumbnail" alt="Nasi Lekarze" src="<?= $this->baseUrl.$link;?>"/> 
  <figcaption class="figure-caption">W celu zmiany zdjęciu wybierz je z komputera.</figcaption>
</figure>        
             
  
    </div>
    </div>
    <div class="col-sm-6">
        <?php
        echo $this->formFile($file);
        $file->getMessages();
        echo $this->formElementErrors()->render($file, ['class' => 'text-danger']);
        ?>
    </div>
    
</div> 
      
	
</div>
 <div class="col-sm-12  btn btn-secondary btn-lg btn-block">
<?=  $this->formHidden($hiddenId);  ?>    
<?=  $this->formSubmit($submit);  ?>
	</div>
    </div>
        </div>
</div>
  <?= $this->form()->closeTag();  ?>


<script type="text/javascript">
                  // Replace the <textarea id="editor1"> with a CKEditor 4
                // instance, using default configuration.
   CKEDITOR.replace( 'opis', {
  language: 'pl',
   uiColor: '#9AB8F3'
});
    
const check_pesel="http://localhost/przychodniadwa/check_pesel";

		$( document ).ready( function () {
                    
                    $( "input:blank" ).css( "background-color", "#bbbbff" );
                    
			$("#dodaj_form_lekarz").validate( {
				rules: {
					"lekarz_fieldset[imie]": 
                                                {
                                                    required: true,
                                                    minlength: 2,
                                                    polskieznaki: true,
                                                },
					"lekarz_fieldset[nazwisko]": 
                                                {
                                                    required: true,
                                                    minlength: 2,
                                                    polskieznaki: true,
                                                },
                                        "lekarz_fieldset[pesel]":
                                                {
						required: true,
                                                pesel: true,
                                                 remote: {
                                                   url: check_pesel,
                                                    type: "POST",
                                                   data: {
                                                    pesel: function() {
                                                    return $( "#pesel" ).val();
                                                                    },
                                                    idlekarz: function() {
                                                    return $( "#idlekarz" ).val();
                                                                    },
                                                         },     
                                                        },
                                                 },
                                        "lekarz_fieldset[mail]":
                                                {
						required: true,
                                                email: true,
                                                 },         
						
					confirm_mail:  {
						required: true,
                                                equalTo: "#mail",
						
					},
					 "lekarz_fieldset[specjalnosc]": {
						polskieznaki: true,
					},
					email: {
						required: true,
						email: true,
					},
					agree: "required",
				},
				messages: {
					"lekarz_fieldset[imie]": 
                                                {
                                                required: "Please enter a imię", 
                                                minlength: "Your imie must consist of at least 2 characters"
                                                },
					"lekarz_fieldset[nazwisko]": 
                                                 {
                                                required: "Please enter a nazwisko", 
                                                minlength: "Your imie must consist of at least 2 characters"
                                                },
					   "lekarz_fieldset[pesel]":
                                                   {
						required: "Numer PESEL jest obowiązkowy",
                                                pesel: "Wprowadź poprawny numer PESEL",
                                                remote: jQuery.validator.format("{0} jest już używany. Zmień na inny")
                                                    },
                                             "lekarz_fieldset[mail]":
                                                   {
						required: "Mail jest obowiązkowy",
                                                email: "Wprowadź poprawny format Maila",
                                                    },        
                                             "lekarz_fieldset[specjalnosc]": 
                                                {
						polskieznaki: "Wymagany polski format znaków",
					},
					confirm_password: {
						required: "Please provide a password",
						minlength: "Your password must be at least 5 characters long",
						equalTo: "Please enter the same password as above"
					},
					email: "Please enter a valid email address",
					agree: "Please accept our policy"
				},
				errorElement: "em",
				errorPlacement: function ( error, element ) {
					// Add the `invalid-feedback` class to the error element
					error.addClass( "invalid-feedback" );

					if ( element.prop( "type" ) === "checkbox" ) {
						error.insertAfter( element.next( "label" ) );
					} else {
						error.insertAfter( element );
					}
				},
				highlight: function ( element, errorClass, validClass ) {
					$( element ).addClass( "is-invalid" ).removeClass( "is-valid" );
				},
				unhighlight: function (element, errorClass, validClass) {
					$( element ).addClass( "is-valid" ).removeClass( "is-invalid" );
				}
			} );

		} );
	</script>