<?php
$title = 'Lakarze Przychodni';
$this->headTitle($title);

/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<div class="jumbotron" style="margin-top: 10px;padding-top: 10px; padding-bottom: 10px;" >
    <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="<?= $this->basePath('img/karuzela/1.jpg') ?>" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="<?= $this->basePath('img/karuzela/2.jpg') ?>" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="<?= $this->basePath('img/karuzela/3.jpg') ?>" class="d-block w-100" alt="...">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Poprzedni</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Następny</span>
  </a>
</div>
</div>

<div>
        <?= $this->partial('partial/flashMessenger.phtml'); ?>
</div>

<div class="card-deck" id="pobierz">
       
<?php  foreach ($this->paginator as $lekarz): ?>
            
    <div class="card">
        <h2 class="card-header"><?= $lekarz->getImie().' '.$lekarz->getNazwisko();?></h2>
        <div class="card-body">
            <div class="border bg-light">
   
         <div style="float: left;margin-right: 5px">
             <?php
             
            $link=$lekarz->getZdjecie();
              if(!$link){
                 $link='/public/img/Anonymous_male.jpg';
              }
              
             ?>
             
            <img width="200" class="rounded mx-auto d-block img-thumbnail" alt="Nasi Lekarze" src="<?= $this->baseUrl.$link;?>"/> 
        </div>
        <div>
            <span><?= $lekarz->getOpis(); ?></span></n>   
        </div>
         <div>
             <span>Specjalność: <?= $lekarz->getSpecjalnosc(); ?> </span>     
        </div>
        <div>
         <span>Telefon: <?= $lekarz->getTelefon(); ?> </span>   
        </div>
        <div>
             <span>Mail: <?= $lekarz->getMail(); ?> </span>     
        </div>     
         
    </div>
            <a class="btn btn-primary" href="<?= $this->url('lekarz', ['action' => 'pokaz','id'=>$lekarz->getIdlekarz()]) ?>">Umów wizytę &raquo;</a>
        </div>
    </div>

    
        <?php endforeach; ?>
    

   
       
</div>

<div class="jumbotron" style="margin-top: 10px;margin-bottom: 5px;padding-top: 10px; padding-bottom: 1px;">
<?= $this->paginationControl(
    // The paginator object:
    $this->paginator,
    // The scrolling style:
    'sliding',
    // The partial to use to render the control:
    'partial/paginator',
    // The route to link to when a user clicks a control link:
    ['route' => 'lekarze']
) ?>

</div>

